### ISSUE TITLE
Problem starting NVIDIADeepStreamSDK

### ISSUE THREAD

**Issue by codeblazar** [toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure#12]
Originally had the same issue as the video with ...

              "DISPLAY": {
                "value": ":0"
              }

I'm unsure why. Sometimes I reboot and it's 1, sometimes 0. Anyway, I followed the video advice and simply 'matched' the output from **echo $DISPLAY** with the value in the DISPLAY value in the **deployment.template.json**. Unfortunately I didn't get the same result as you did. Mine still fails. 

NVIDIA developer forums make some suggestions, here: https://forums.developer.nvidia.com/t/error-failed-to-create-element-src-bin-muxer-while-trying-to-run-a-modified-test5-on-nvidia-deepstream-container/126485 but unfortunately I'm not sure how to apply them.

Output from **docker logs -f NVIDIADeepStreamSDK** below:

Any help would be greatly appreciated :)

CHeers.

nvbufsurftransform: Could not get EGL display connection
2020-12-28 15:02:19.482779: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
No protocol specified
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No protocol specified
**repeats**
nvbufsurftransform: Could not get EGL display connection
No protocol specified
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed

**Comment by toolboc** [comment]
Hi @Nezakka, 

It sounds like you are on the right path, in addition to specifying the appropriate value for `DISPLAY` in your deployment template, you must also configure permissions to allow the 'iotedge' user access to the X11 service if attempting to use EGL sink from an IoT Edge workload.  Make sure that you have followed the instructions for this mentioned in [Module 2.3](https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/blob/master/docs/Module%202%20-%20Configure%20and%20Deploy%20Intelligent%20Video%20Analytics%20to%20IoT%20Edge%20Runtime%20on%20NVIDIA%20Jetson.md#module-23--prepare-the-jetson-device-to-use-the-intelligent-video-analytics-sample-configurations) as this will enable a persistent mechanism that is required for retaining these permission on subsequent reboots.  Additional details on the topic of "Visualizing results from a containerized instance of NVIDIA DeepStream" are also mentioned in [this article](https://www.hackster.io/pjdecarlo/custom-object-detection-with-csi-ir-camera-on-nvidia-jetson-c6d315#toc-visualizing-results-from-a-containerized-instance-of-nvidia-deepstream-4) which may provide some assistance / explanation.

I've distilled this information into a checklist that should contain all of the necessary steps to allow for X11 access from the DeepStream SDK module.

Steps to allow access to X11 from an Iot Edge Workload:
- [ ] [Ensure that persistent access to X11 services has been granted to the "iotedge" user](https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/blob/master/docs/Module%202%20-%20Configure%20and%20Deploy%20Intelligent%20Video%20Analytics%20to%20IoT%20Edge%20Runtime%20on%20NVIDIA%20Jetson.md#module-23--prepare-the-jetson-device-to-use-the-intelligent-video-analytics-sample-configurations)
- [ ] [Ensure that the X11 socket is accessible to the container](https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/blob/master/deployment-iothub/deployment.template.json#L79)
- [ ] [Ensure a proper value is provided for the `DISPLAY` environment variable](https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/blob/master/deployment-iothub/deployment.template.json#L92) 
See: [Visualizing results from a containerized instance of NVIDIA DeepStream](https://www.hackster.io/pjdecarlo/custom-object-detection-with-csi-ir-camera-on-nvidia-jetson-c6d315#toc-visualizing-results-from-a-containerized-instance-of-nvidia-deepstream-4)

As a last resort, you could always modify your DeepStream configuration to instead use the Overlay Sink or RTSP sink (instead of EGL) as these mechanisms do not require access to X11.  There are pros / cons to either approach (Overlay will draw directly to the framebuffer / RTSP will require viewing output using an RTSP client) but it may help you to move forward if you find yourself stuck.

**Comment by codeblazar** [comment]
Hi Paul,

That's totally on me. I had forgotten about the X11 settings. Initially I tried on JetPack 4.3 following other tutorials but had problems so I upgraded the nano to 4.4. Somehow I omitted a few steps. Thanks for the great support, the links and the quick response.
