### ISSUE TITLE
docker logs tend to get very large volume and eat system disk space

### ISSUE THREAD

**Issue by guybartal** [toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure#4]
Docker logs tend to get very large volume and eat system disk space causing to lose the ability to reboot,
I lost twice my Jetson Xavier like that... 😥 

I've written a simple cronjob to truncate all docker containers logs every hour:

edit the crontab file using your favorite editor, for example:
`sudo nano /etc/crontab`

add this command to the file:
`0 *     * * *   root    find /var/lib/docker/containers/  *-json.log -exec truncate -s 0 {} +`

I guess you can make it better, I'm not a Linux expert :)

**Comment by toolboc** [comment]
Depending on needs, it is possible to configure per-module logging settings within the IoT Edge deployment manifest as shown [here](https://stackoverflow.com/questions/58060489/log-rotation-on-iot-edge-agent).  It is also possible to [configure max-log size on the docker daemon](https://docs.docker.com/config/containers/logging/configure/#configure-the-default-logging-driver) (which will effect all containerized workloads).

How much total space was available on your device before system disk space was exhausted?  I ask because I've ran this and similar workloads for many months without interruption without experiencing the issue.  I assume it might be due to my use of 64GB+ SD cards on all devices and that the system log rotation was possibly helping out behind the scenes.  In any event, this issue is very much valid, I'm curious if it is more prevalent on smaller sized SD setups.

**Comment by guybartal** [comment]
Thanks for the tips @toolboc! I’ll update my partners, in my case it was Xavier with 8GB for the system volume and the docker process ate all my disk space... I had this event twice until I figured it out that the docker was the root cause...
and you probably know how painful it is to initialize Xavier with an Ubuntu host comparing to a simple image on the Nano and NX devices...
